{% set name = "opt_einsum" %}
{% set version = "3.1.0" %}
{% set sha256 = "edfada4b1d0b3b782ace8bc14e80618ff629abf53143e1e6bbf9bd00b11ece77" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python >=3.5
    - setuptools
  run:
    - python >=3.5
    - numpy

test:
  requires:
    - python >=3.5
    - pytest
  commands:
    - pytest --pyargs opt_einsum

about:
  home: http://github.com/dgasmith/opt_einsum
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Optimizing einsum functions in NumPy, Tensorflow, Dask, and more with contraction order optimization.'

  description: >
    Einsum is a very powerful function for contracting tensors of arbitrary dimension and index.
    However, it is typically only optimized to contract two terms at a time resulting in non-optimal scaling.
    This package optimizes the contraction order for arbitrarily large speedups.

    See the docs for more information: http://optimized-einsum.readthedocs.io
    
  dev_url: https://github.com/dgasmith/opt_einsum

extra:
  recipe-maintainers:
    - dgasmith
    - loriab
