{% set name = "opt_einsum" %}
{% set version = "2.3.2" %}
{% set sha256 = "d3d464b4da7ef09e444c30e4003a27def37f85ff10ff2671e5f7d7813adac35b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy

test:
  requires:
    - python
    - pytest
  commands:
    - py.test --pyargs opt_einsum

about:
  home: http://github.com/dgasmith/opt_einsum
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A contraction order optimizer for the NumPy Einsum function and other backends.'

  description: >
    Einsum is a very powerful function for contracting tensors of arbitrary dimension and index.
    However, it is only optimized to contract two terms at a time resulting in non-optimal scaling.
    This package optimizes the contraction order for arbitrarily large speedups.

    See the docs for more information: http://optimized-einsum.readthedocs.io/en/latest/?badge=latest
    
  dev_url: https://github.com/dgasmith/opt_einsum

extra:
  recipe-maintainers:
    - dgasmith
    - loriab
