{% set name = "opt_einsum" %}
{% set version = "3.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 96ca72f1b886d148241348783498194c577fa30a8faac108586b14f1ba4473ac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<38]

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-fancy-pypi-readme >=22.5.0
    - hatch-vcs
  run:
    - python
    # numpy is not in requirements but used in source code
    - numpy

test:
  imports:
    - opt_einsum
  commands:
    - pytest --verbose --pyargs opt_einsum
    - pip check
  requires:
    - pip
    - pytest
    - pytest-pep8

about:
  home: http://github.com/dgasmith/opt_einsum
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Optimizing einsum functions in NumPy, Tensorflow, Dask, and more with contraction order optimization.
  description: |
    Einsum is a very powerful function for contracting tensors of arbitrary dimension and index. However, it is typically only optimized to contract two terms at a time resulting in non-optimal scaling. This package optimizes the contraction order for arbitrarily large speedups.
    See the docs for more information: http://optimized-einsum.readthedocs.io
  dev_url: https://github.com/dgasmith/opt_einsum
  doc_url: http://optimized-einsum.readthedocs.io

extra:
  recipe-maintainers:
    - dgasmith
    - loriab
    - xhochy
