travis:
  secure:
    BINSTAR_TOKEN: ToEgwpQ1EFBTzby6vwOqsl5mUnljTZ3YEc/D7nw64LNH4EN0dKZL55QMT0GaSOw1P0OgyIastApB+nmn9t2Yxmon7qCSHzhVqwV0KG8VelLkooX/bXjli6mIRYTygFPtMO75PtgSuo8uSVUO3pbO/YctWZ4e/WJ4INoUEQAcXWqhj5lQOv+XdgIdvGP135AOreBafNS6PiUfAzY6vJI9YaOiVcNfA6whVQasT9bcKDBcwayJERO1vQIDGAiIWMRCX8uTX40ZOdYqqtX+OJW2TcqufM9qauH6k4ANw6HobHtsZhu0/wdD3NHjQJN+nKAIDsageEITLXHa/jXzmyqneroYzukFd0AD0YlbjG7ysK65Ayh0Y2nHB/fP55V7X5AiNQiO7XaR4/aOaBvgFGdFd/ddECX+50q5ySdcVEejwB5FnVK6u+7mmi4eWViJg3y3S4+FJocRgA72e1HoXNsVHBkfaqjvn/Z5WV4kIzZGy4kXozJFD8er4QJ3955lS8KGN3GIDbO2M6pIQI+CcHG2xQkZtieonXv9AkPLTqaeQde7VmrOLgSs5mR1XhftSGVjRFSmE5Kwk4wzt2Q/97S0fNyMzMmsYMwPvNb22XsIjwevBDuwThl/yb5ISbe7F19aW2XNazH8h7OkSDlp0rf0IG5AR93XvzfCttQiwc7BPDU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
