travis:
  secure:
    BINSTAR_TOKEN: 1QfT3hckzEK0JNM62rujAc6fyP0fMHY7TUl9dC/F9MAcGW9IB/XnCEI9Svfh5wgA0f9W2C4TApvex4EOB68Jp2mCsARHfZBCmFY/KAuroVjrY2XrO15R/fQ/F8feI4825GS2dR0GBTwa0SxjTzk7RP/PF5nrOgT0Do8CoTgUjPR6pXuHsE2BRAlFbHjcPxcrF1AKEfR/7zjHXHaDSET+9A/coMtiF0TWW/Iq4rimRtCAoxaIxR5QmXqYtYy5rEKBXhe4qnp45hXHSkPpkOEP8FDXAjcC4Yqyk/R5+O4jV/d1TgB98akNaJ6QujiCXhgdN4oAWeQ1Qwyox3gslI9nn/ym8ZchLYA+9hDk+rvTGKIcm/t2bKT1v30TO2mLDoIeglSLZAfxRtJhHD1ENR05KjldnfSGgYEkjHG0D+AtLVWQ7sPvX5wsyrPoxqc4f1y/0StPs82L4oHULxKEjMbWpxhWGp+s37ZZo+lQ7r/DqR46bccfQmQ/o3IS7guLPrTccMgOusR8Tv+u/MAATmAhA1NwpHEXIAdnP4PqKpP9bR2AaPn5nHRkgNrebMB2R8JIa9lY1Erh1ir3iGck36MSAZmnBy+IGEvujqvS7ycD+wIbTysWCPVD0KRCS7G/ggbIRkCFetr8novuTjTBklux/8ZMMeVxYeE2Li3zLdXVRFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
